name: Replace tzdev

on:
  workflow_dispatch:  # Elle çalıştırmak için

jobs:
  replace-tzdev:
    runs-on: ubuntu-latest

    steps:
    - name: Bu repoyu klonla (ramdisk branch)
      uses: actions/checkout@v4
      with:
        ref: Ramdisk  # Hedef branch

    - name: Git kullanıcı bilgilerini ayarla
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: FreshROMs reposunu klonla
      run: |
        git clone --depth=1 --branch wip https://github.com/sundrams-playground/kernel_samsung_exynos9610.git temp-sundrams-playground

    - name: Mevcut tzdev klasörünü değiştir
      run: |
        rm -rf drivers/misc/tzdev
        cp -r temp-sundrams-playground/drivers/misc/tzdev drivers/misc/

    - name: Değişiklikleri commit et
      run: |
        git add drivers/misc/tzdev
        git commit -m "update tzdev"

    - name: Değişiklikleri ramdisk branch'ine push et
      run: |
        git push origin Ramdisk --force
